/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */


#ifndef SWIG_TEMPLATE_DISAMBIGUATOR
#  if defined(__SUNPRO_CC) 
#    define SWIG_TEMPLATE_DISAMBIGUATOR template
#  else
#    define SWIG_TEMPLATE_DISAMBIGUATOR 
#  endif
#endif

/* ruby.swg */
/* Implementation : RUBY */
#define SWIGRUBY 1

#include "ruby.h"

/* Flags for pointer conversion */
#define SWIG_POINTER_EXCEPTION     0x1
#define SWIG_POINTER_DISOWN        0x2

#define NUM2USHRT(n) (\
    (0 <= NUM2UINT(n) && NUM2UINT(n) <= USHRT_MAX)\
    ? (unsigned short) NUM2UINT(n) \
    : (rb_raise(rb_eArgError, "integer %d out of range of `unsigned short'",\
               NUM2UINT(n)), (short)0)\
)

#define NUM2SHRT(n) (\
    (SHRT_MIN <= NUM2INT(n) && NUM2INT(n) <= SHRT_MAX)\
    ? (short)NUM2INT(n)\
    : (rb_raise(rb_eArgError, "integer %d out of range of `short'",\
               NUM2INT(n)), (short)0)\
)

/* Ruby 1.7 defines NUM2LL(), LL2NUM() and ULL2NUM() macros */
#ifndef NUM2LL
#define NUM2LL(x) NUM2LONG((x))
#endif
#ifndef LL2NUM
#define LL2NUM(x) INT2NUM((long) (x))
#endif
#ifndef ULL2NUM
#define ULL2NUM(x) UINT2NUM((unsigned long) (x))
#endif

/* Ruby 1.7 doesn't (yet) define NUM2ULL() */
#ifndef NUM2ULL
#ifdef HAVE_LONG_LONG
#define NUM2ULL(x) rb_num2ull((x))
#else
#define NUM2ULL(x) NUM2ULONG(x)
#endif
#endif

/*
 * Need to be very careful about how these macros are defined, especially
 * when compiling C++ code or C code with an ANSI C compiler.
 *
 * VALUEFUNC(f) is a macro used to typecast a C function that implements
 * a Ruby method so that it can be passed as an argument to API functions
 * like rb_define_method() and rb_define_singleton_method().
 *
 * VOIDFUNC(f) is a macro used to typecast a C function that implements
 * either the "mark" or "free" stuff for a Ruby Data object, so that it
 * can be passed as an argument to API functions like Data_Wrap_Struct()
 * and Data_Make_Struct().
 */
 
#ifdef __cplusplus
#  ifndef RUBY_METHOD_FUNC /* These definitions should work for Ruby 1.4.6 */
#    define PROTECTFUNC(f) ((VALUE (*)()) f)
#    define VALUEFUNC(f) ((VALUE (*)()) f)
#    define VOIDFUNC(f)  ((void (*)()) f)
#  else
#    ifndef ANYARGS /* These definitions should work for Ruby 1.6 */
#      define PROTECTFUNC(f) ((VALUE (*)()) f)
#      define VALUEFUNC(f) ((VALUE (*)()) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    else /* These definitions should work for Ruby 1.7+ */
#      define PROTECTFUNC(f) ((VALUE (*)(VALUE)) f)
#      define VALUEFUNC(f) ((VALUE (*)(ANYARGS)) f)
#      define VOIDFUNC(f)  ((RUBY_DATA_FUNC) f)
#    endif
#  endif
#else
#  define VALUEFUNC(f) (f)
#  define VOIDFUNC(f) (f)
#endif

typedef struct {
  VALUE klass;
  VALUE mImpl;
  void  (*mark)(void *);
  void  (*destroy)(void *);
} swig_class;

/* Don't use for expressions have side effect */
#ifndef RB_STRING_VALUE
#define RB_STRING_VALUE(s) (TYPE(s) == T_STRING ? (s) : (*(volatile VALUE *)&(s) = rb_str_to_str(s)))
#endif
#ifndef StringValue
#define StringValue(s) RB_STRING_VALUE(s)
#endif
#ifndef StringValuePtr
#define StringValuePtr(s) RSTRING(RB_STRING_VALUE(s))->ptr
#endif
#ifndef StringValueLen
#define StringValueLen(s) RSTRING(RB_STRING_VALUE(s))->len
#endif
#ifndef SafeStringValue
#define SafeStringValue(v) do {\
    StringValue(v);\
    rb_check_safe_str(v);\
} while (0)
#endif

#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
#define rb_define_alloc_func(klass, func) rb_define_singleton_method((klass), "new", VALUEFUNC((func)), -1)
#define rb_undef_alloc_func(klass) rb_undef_method(CLASS_OF((klass)), "new")
#endif

/* Contract support */

#define SWIG_contract_assert(expr, msg) if (!(expr)) { rb_raise(rb_eRuntimeError, (char *) msg ); } else


/***********************************************************************
 * swigrun.swg
 *
 *     This file contains generic CAPI SWIG runtime support for pointer
 *     type checking.
 *
 ************************************************************************/

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "1"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
#define SWIG_QUOTE_STRING(x) #x
#define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
#define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
#define SWIG_TYPE_TABLE_NAME
#endif

#include <string.h>

#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#  define SWIGINLINE inline
#else
#  define SWIGINLINE
#endif
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the swig runtime code.
  In 99.9% of the cases, swig just needs to declare them as 'static'.
  
  But only do this if is strictly necessary, ie, if you have problems
  with your compiler or so.
*/
#ifndef SWIGRUNTIME
#define SWIGRUNTIME static
#endif
#ifndef SWIGRUNTIMEINLINE
#define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

typedef struct swig_type_info {
  const char             *name;
  swig_converter_func     converter;
  const char             *str;
  void                   *clientdata;
  swig_dycast_func        dcast;
  struct swig_type_info  *next;
  struct swig_type_info  *prev;
} swig_type_info;

/* 
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return *f1 - *f2;
  }
  return (l1 - f1) - (l2 - f2);
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  int equiv = 0;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (!equiv && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te) == 0;
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Register a type mapping with the type-checking
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeRegisterTL(swig_type_info **tl, swig_type_info *ti) {
  swig_type_info *tc, *head, *ret, *next;
  /* Check to see if this type has already been registered */
  tc = *tl;
  while (tc) {
    /* check simple type equivalence */
    int typeequiv = (strcmp(tc->name, ti->name) == 0);   
    /* check full type equivalence, resolving typedefs */
    if (!typeequiv) {
      /* only if tc is not a typedef (no '|' on it) */
      if (tc->str && ti->str && !strstr(tc->str,"|")) {
	typeequiv = SWIG_TypeEquiv(ti->str,tc->str);
      }
    }
    if (typeequiv) {
      /* Already exists in the table.  Just add additional types to the list */
      if (ti->clientdata) tc->clientdata = ti->clientdata;
      head = tc;
      next = tc->next;
      goto l1;
    }
    tc = tc->prev;
  }
  head = ti;
  next = 0;

  /* Place in list */
  ti->prev = *tl;
  *tl = ti;

  /* Build linked lists */
  l1:
  ret = head;
  tc = ti + 1;
  /* Patch up the rest of the links */
  while (tc->name) {
    head->next = tc;
    tc->prev = head;
    head = tc;
    tc++;
  }
  if (next) next->prev = head;
  head->next = next;

  return ret;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  swig_type_info *s;
  if (!ty) return 0;        /* Void pointer */
  s = ty->next;             /* First element always just a name */
  do {
    if (strcmp(s->name,c) == 0) {
      if (s == ty->next) return s;
      /* Move s to the top of the linked list */
      s->prev->next = s->next;
      if (s->next) {
        s->next->prev = s->prev;
      }
      /* Insert s as second element in the list */
      s->next = ty->next;
      if (ty->next) ty->next->prev = s;
      ty->next = s;
      s->prev = ty;
      return s;
    }
    s = s->next;
  } while (s && (s != ty->next));
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_type_info *ty, void *ptr) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr);
}

/* 
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  We choose
     to print the last name, as it is often (?) the most
     specific. */
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
  Search for a swig_type_info structure
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryTL(swig_type_info *tl, const char *name) {
  swig_type_info *ty = tl;
  while (ty) {
    if (ty->str && (SWIG_TypeEquiv(ty->str,name))) return ty;
    if (ty->name && (strcmp(name,ty->name) == 0)) return ty;
    ty = ty->prev;
  }
  return 0;
}

/* 
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientDataTL(swig_type_info *tl, swig_type_info *ti, void *clientdata) {
  swig_type_info *tc, *equiv;
  if (ti->clientdata) return;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;
  equiv = ti->next;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0))
          SWIG_TypeClientDataTL(tl,tc,clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static char hex[17] = "0123456789abcdef";
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  register unsigned char uu;
  for (; u != eu; ++u) {
    uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/* 
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  register unsigned char *u = (unsigned char *) ptr;
  register const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    register int d = *(c++);
    register unsigned char uu = 0;
    if ((d >= '0') && (d <= '9'))
      uu = ((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = ((d - ('a'-10)) << 4);
    else 
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (d - ('a'-10));
    else 
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
  This function will propagate the clientdata field of type to any new
  swig_type_info structures that have been added into the list of
  equivalent types.  It is like calling SWIG_TypeClientData(type,
  clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientDataTL(swig_type_info *tl, swig_type_info *type) {
  swig_type_info *equiv = type->next;
  swig_type_info *tc;
  if (!type->clientdata) return;
  while (equiv) {
    if (!equiv->converter) {
      tc = tl;
      while (tc) {
        if ((strcmp(tc->name, equiv->name) == 0) && !tc->clientdata)
          SWIG_TypeClientDataTL(tl,tc, type->clientdata);
        tc = tc->prev;
      }
    }
    equiv = equiv->next;
  }
}

/* 
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/***********************************************************************
 * common.swg
 *
 *     This file contains generic SWIG runtime support for pointer
 *     type checking as well as a few commonly used macros to control
 *     external linkage.
 *
 * Author : David Beazley (beazley@cs.uchicago.edu)
 *
 * Copyright (c) 1999-2000, The University of Chicago
 * 
 * This file may be freely redistributed without license or fee provided
 * this copyright message remains intact.
 ************************************************************************/


#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#  if !defined(STATIC_LINKED)
#    define SWIGEXPORT(a) __declspec(dllexport) a
#  else
#    define SWIGEXPORT(a) a
#  endif
#else
#  define SWIGEXPORT(a) a
#endif

#ifdef __cplusplus
extern "C" {
#endif


/*************************************************************************/


/* The static type info list */

static swig_type_info *swig_type_list = 0;
static swig_type_info **swig_type_list_handle = &swig_type_list;
  

/* Register a type mapping with the type-checking */
static swig_type_info *
SWIG_TypeRegister(swig_type_info *ti) {
  return SWIG_TypeRegisterTL(swig_type_list_handle, ti);
}

/* Search for a swig_type_info structure */
static swig_type_info *
SWIG_TypeQuery(const char *name) {
  return SWIG_TypeQueryTL(*swig_type_list_handle, name);
}

/* Set the clientdata field for a type */
static void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientDataTL(*swig_type_list_handle, ti, clientdata);
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
static void
SWIG_PropagateClientData(swig_type_info *type) {
  SWIG_PropagateClientDataTL(*swig_type_list_handle, type);
}

#ifdef __cplusplus
}
#endif

/* Common SWIG API */
#define SWIG_ConvertPtr(obj, pp, type, flags) \
  SWIG_Ruby_ConvertPtr(obj, pp, type, flags)
#define SWIG_NewPointerObj(p, type, flags) \
  SWIG_Ruby_NewPointerObj(p, type, flags)
#define SWIG_MustGetPtr(p, type, argnum, flags) \
  SWIG_Ruby_MustGetPtr(p, type, argnum, flags)

/* Ruby-specific SWIG API */

#define SWIG_InitRuntime() \
  SWIG_Ruby_InitRuntime()
#define SWIG_define_class(ty) \
  SWIG_Ruby_define_class(ty)
#define SWIG_NewClassInstance(value, ty) \
  SWIG_Ruby_NewClassInstance(value, ty)
#define SWIG_MangleStr(value) \
  SWIG_Ruby_MangleStr(value)
#define SWIG_CheckConvert(value, ty) \
  SWIG_Ruby_CheckConvert(value, ty)
#define SWIG_NewPackedObj(ptr, sz, ty) \
  SWIG_Ruby_NewPackedObj(ptr, sz, ty)
#define SWIG_ConvertPacked(obj, ptr, sz, ty, flags) \
  SWIG_Ruby_ConvertPacked(obj, ptr, sz, ty, flags)

/* rubydef.swg */
#ifdef __cplusplus
extern "C" {
#endif

static VALUE _mSWIG = Qnil;
static VALUE _cSWIG_Pointer = Qnil;
static VALUE swig_runtime_data_type_pointer = Qnil;

/* Initialize Ruby runtime support */
static void
SWIG_Ruby_InitRuntime(void)
{
    VALUE pointer;
    
    if (_mSWIG == Qnil) {
        _mSWIG = rb_define_module("SWIG");
    }
    
    /* first check if pointer already created */
    pointer = rb_gv_get("$swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME);
    if (pointer != Qnil) {
      Data_Get_Struct(pointer, swig_type_info *, swig_type_list_handle);
    } else {
      /* register a new class */
      VALUE cl = rb_define_class("swig_runtime_data", rb_cObject);
      /* create and store the structure pointer to a global variable */
      swig_runtime_data_type_pointer = Data_Wrap_Struct(cl, 0, 0, swig_type_list_handle);
      rb_define_readonly_variable("$swig_runtime_data_type_pointer" SWIG_RUNTIME_VERSION SWIG_TYPE_TABLE_NAME, &swig_runtime_data_type_pointer);
    }
}

/* Define Ruby class for C type */
static void
SWIG_Ruby_define_class(swig_type_info *type)
{
    VALUE klass;
    char *klass_name = (char *) malloc(4 + strlen(type->name) + 1);
    sprintf(klass_name, "TYPE%s", type->name);
    if (NIL_P(_cSWIG_Pointer)) {
	_cSWIG_Pointer = rb_define_class_under(_mSWIG, "Pointer", rb_cObject);
	rb_undef_method(CLASS_OF(_cSWIG_Pointer), "new");
    }
    klass = rb_define_class_under(_mSWIG, klass_name, _cSWIG_Pointer);
    free((void *) klass_name);
}

/* Create a new pointer object */
static VALUE
SWIG_Ruby_NewPointerObj(void *ptr, swig_type_info *type, int own)
{
    char *klass_name;
    swig_class *sklass;
    VALUE klass;
    VALUE obj;
    
    if (!ptr)
	return Qnil;
    
    if (type->clientdata) {
      sklass = (swig_class *) type->clientdata;
      obj = Data_Wrap_Struct(sklass->klass, VOIDFUNC(sklass->mark), (own ? VOIDFUNC(sklass->destroy) : 0), ptr);
    } else {
      klass_name = (char *) malloc(4 + strlen(type->name) + 1);
      sprintf(klass_name, "TYPE%s", type->name);
      klass = rb_const_get(_mSWIG, rb_intern(klass_name));
      free((void *) klass_name);
      obj = Data_Wrap_Struct(klass, 0, 0, ptr);
    }
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Create a new class instance (always owned) */
static VALUE
SWIG_Ruby_NewClassInstance(VALUE klass, swig_type_info *type)
{
    VALUE obj;
    swig_class *sklass = (swig_class *) type->clientdata;
    obj = Data_Wrap_Struct(klass, VOIDFUNC(sklass->mark), VOIDFUNC(sklass->destroy), 0);
    rb_iv_set(obj, "__swigtype__", rb_str_new2(type->name));
    return obj;
}

/* Get type mangle from class name */
static SWIGINLINE char *
SWIG_Ruby_MangleStr(VALUE obj)
{
  VALUE stype = rb_iv_get(obj, "__swigtype__");
  return StringValuePtr(stype);
}

/* Convert a pointer value */
static int
SWIG_Ruby_ConvertPtr(VALUE obj, void **ptr, swig_type_info *ty, int flags)
{
  char *c;
  swig_type_info *tc;

  /* Grab the pointer */
  if (NIL_P(obj)) {
    *ptr = 0;
    return 0;
  } else {
    Data_Get_Struct(obj, void, *ptr);
  }
  
  /* Do type-checking if type info was provided */
  if (ty) {
    if (ty->clientdata) {
        if (rb_obj_is_kind_of(obj, ((swig_class *) (ty->clientdata))->klass)) {
          if (*ptr == 0)
            rb_raise(rb_eRuntimeError, "This %s already released", ty->str);
          return 0;
        }
    }
    if ((c = SWIG_MangleStr(obj)) == NULL) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) {
      if (flags & SWIG_POINTER_EXCEPTION)
        rb_raise(rb_eTypeError, "Expected %s", ty->str);
      else
        return -1;
    }
    *ptr = SWIG_TypeCast(tc, *ptr);
  }
  return 0;
}

/* Convert a pointer value, signal an exception on a type mismatch */
static SWIGINLINE void *
SWIG_Ruby_MustGetPtr(VALUE obj, swig_type_info *ty, int argnum, int flags)
{
  void *result;
  SWIG_ConvertPtr(obj, &result, ty, flags | SWIG_POINTER_EXCEPTION);
  return result;
}

/* Check convert */
static SWIGINLINE int
SWIG_Ruby_CheckConvert(VALUE obj, swig_type_info *ty)
{
  char *c = SWIG_MangleStr(obj);
  if (!c)
    return 0;
  return SWIG_TypeCheck(c,ty) != 0;
}

static VALUE
SWIG_Ruby_NewPackedObj(void *ptr, int sz, swig_type_info *type) {
  char result[1024];
  char *r = result;
  if ((2*sz + 1 + strlen(type->name)) > 1000) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r, ptr, sz);
  strcpy(r, type->name);
  return rb_str_new2(result);
}

/* Convert a packed value value */
static void
SWIG_Ruby_ConvertPacked(VALUE obj, void *ptr, int sz, swig_type_info *ty, int flags) {
  swig_type_info *tc;
  const char  *c;

  if (TYPE(obj) != T_STRING) goto type_error;
  c = StringValuePtr(obj);
  /* Pointer values must start with leading underscore */
  if (*c != '_') goto type_error;
  c++;
  c = SWIG_UnpackData(c, ptr, sz);
  if (ty) {
    tc = SWIG_TypeCheck(c, ty);
    if (!tc) goto type_error;
  }
  return;

type_error:

  if (flags) {
    if (ty) {
      rb_raise(rb_eTypeError, "Type error. Expected %s", ty->name);
    } else {
      rb_raise(rb_eTypeError, "Expected a pointer");
    }
  }
}

#ifdef __cplusplus
}
#endif



/* -------- TYPES TABLE (BEGIN) -------- */

#define  SWIGTYPE_p_unsigned_long swig_types[0] 
#define  SWIGTYPE_p_anthy_conv_stat swig_types[1] 
#define  SWIGTYPE_p_anthy_segment_stat swig_types[2] 
#define  SWIGTYPE_p_anthy_context swig_types[3] 
#define  SWIGTYPE_p_anthy_prediction_stat swig_types[4] 
static swig_type_info *swig_types[6];

/* -------- TYPES TABLE (END) -------- */

#define SWIG_init    Init_anthy
#define SWIG_name    "Anthy"

static VALUE mAnthy;

static void SWIG_AsVal(VALUE obj, int *val)
{
    *val = (int) NUM2INT(obj);
}


#ifdef __cplusplus
extern "C" {
#endif
#ifdef HAVE_SYS_TIME_H
# include <sys/time.h>
struct timeval rb_time_timeval(VALUE);
#endif
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif
#include "rubyio.h"
#ifdef __cplusplus
}
#endif


#include "include/anthy.h"


#define anthy_context_set_string anthy_set_string
#define anthy_context_resize_segment anthy_resize_segment
#define anthy_context_get_stat anthy_get_stat
#define anthy_context_get_segment_stat anthy_get_segment_stat
/* #define anthy_context_get_segment anthy_get_segment */
/* #define anthy_context_commit_segment anthy_commit_segment */
#define anthy_context_print anthy_print_context

#define anthy_context_set_prediction_string anthy_set_prediction_string
#define anthy_context_get_prediction_stat anthy_get_prediction_stat
/* #define anthy_context_get_prediction anthy_get_prediction */


static char *
version_string(void)
{
  return anthy_get_version_string();
}


static VALUE logger = Qnil;


#if 0
} /* for c-mode indentation */
#endif

typedef struct logger_info
{
  VALUE level;
  VALUE message;
} logger_info_t;

static VALUE
invoke_logger(VALUE data)
{
  logger_info_t *info = (logger_info_t *)data;
  return rb_funcall(logger, rb_intern("call"), 2, info->level, info->message);
}

static void
rb_logger(int lv, const char *str)
{
  int state = 0;
  logger_info_t info;

  info.level = INT2NUM(lv);
  info.message = rb_str_new2(str);
  rb_protect(invoke_logger, (VALUE)&info, &state);
  if (state && !NIL_P(ruby_errinfo)) {
    VALUE klass, message, backtrace;
    int i, len;

    klass = rb_funcall(rb_funcall(ruby_errinfo, rb_intern("class"), 0),
                       rb_intern("to_s"), 0);
    message = rb_funcall(ruby_errinfo, rb_intern("message"), 0);
    backtrace = rb_funcall(ruby_errinfo, rb_intern("backtrace"), 0);
    rb_warning("%s: %s\n", StringValueCStr(klass), StringValueCStr(message));

    len = RARRAY(backtrace)->len;
    for (i = 0; i < len; i++) {
      rb_warning("%s\n", StringValueCStr(RARRAY(backtrace)->ptr[i]));
    }
  }
}

#if 0
{ /* for c-mode indentation */
#endif


#if 0
} /* for c-mode indentation */
#endif

static void
set_logger(int level)
{
  if (rb_block_given_p()) {
    logger = Qnil;
    anthy_set_logger(NULL, level);
  } else {
    logger = rb_block_proc();
    anthy_set_logger(rb_logger, level);
  }
}

#if 0
{ /* for c-mode indentation */
#endif


swig_class cConvStat;
static void free_anthy_conv_stat(struct anthy_conv_stat *);

swig_class cSegmentStat;
static void free_anthy_segment_stat(struct anthy_segment_stat *);

swig_class cPredictionStat;
static void free_anthy_prediction_stat(struct anthy_prediction_stat *);
int anthy_init(void);
void anthy_quit(void);
void anthy_conf_override(char const *,char const *);
int anthy_set_personality(char const *);
int anthy_commit_prediction(anthy_context_t,int);
char const *anthy_get_version_string(void);
int anthy_set_reconversion_mode(anthy_context_t,int);
static struct anthy_context *new_anthy_context(){
      return anthy_create_context();
    }
static void anthy_context_reset(struct anthy_context *self){
      anthy_reset_context(self);
    }
static VALUE anthy_context_get_segment(struct anthy_context *self,int nth_seg,int nth_cand){
      int len;
      char *buffer;
      len = anthy_get_segment(self, nth_seg, nth_cand, NULL, 0);
      buffer = alloca(len + 1);
      len = anthy_get_segment(self, nth_seg, nth_cand, buffer, len + 1);
      if (len < 0) {
        return Qnil;
      } else {
        return rb_str_new2(buffer);
      }
    }
static VALUE anthy_context_commit_segment(struct anthy_context *self,int s,int c){
      return (anthy_commit_segment(self, s, c) < 0) ? Qfalse : Qtrue;
    }
static int anthy_context_get_prediction(struct anthy_context *self,int nth_pre){
      int len;
      char *buffer;
      len = anthy_get_prediction(self, nth_pre, NULL, 0);
      buffer = alloca(len + 1);
      len = anthy_get_prediction(self, nth_pre, buffer, len + 1);
      if (len < 0) {
        return Qnil;
      } else {
        return rb_str_new2(buffer);
      }
    }

swig_class cContext;
static void free_anthy_context(struct anthy_context *);
static VALUE
_wrap_version_string(int argc, VALUE *argv, VALUE self) {
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (char *)version_string();
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_set_logger(int argc, VALUE *argv, VALUE self) {
    int arg1 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    arg1 = NUM2INT(argv[0]);
    set_logger(arg1);
    
    return Qnil;
}


static VALUE
_wrap_ConvStat_nr_segment_set(int argc, VALUE *argv, VALUE self) {
    struct anthy_conv_stat *arg1 = (struct anthy_conv_stat *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_conv_stat, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->nr_segment = arg2;
    
    return Qnil;
}


static VALUE
_wrap_ConvStat_nr_segment_get(int argc, VALUE *argv, VALUE self) {
    struct anthy_conv_stat *arg1 = (struct anthy_conv_stat *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_conv_stat, 1);
    result = (int) ((arg1)->nr_segment);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_ConvStat_allocate(VALUE self) {
#else
    static VALUE
    _wrap_ConvStat_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_anthy_conv_stat);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_ConvStat(int argc, VALUE *argv, VALUE self) {
    struct anthy_conv_stat *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct anthy_conv_stat *)(struct anthy_conv_stat *) calloc(1, sizeof(struct anthy_conv_stat));
    DATA_PTR(self) = result;
    return self;
}


static void
free_anthy_conv_stat(struct anthy_conv_stat *arg1) {
    free((char *) arg1);
}
static VALUE
_wrap_SegmentStat_nr_candidate_set(int argc, VALUE *argv, VALUE self) {
    struct anthy_segment_stat *arg1 = (struct anthy_segment_stat *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_segment_stat, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->nr_candidate = arg2;
    
    return Qnil;
}


static VALUE
_wrap_SegmentStat_nr_candidate_get(int argc, VALUE *argv, VALUE self) {
    struct anthy_segment_stat *arg1 = (struct anthy_segment_stat *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_segment_stat, 1);
    result = (int) ((arg1)->nr_candidate);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_SegmentStat_seg_len_set(int argc, VALUE *argv, VALUE self) {
    struct anthy_segment_stat *arg1 = (struct anthy_segment_stat *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_segment_stat, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->seg_len = arg2;
    
    return Qnil;
}


static VALUE
_wrap_SegmentStat_seg_len_get(int argc, VALUE *argv, VALUE self) {
    struct anthy_segment_stat *arg1 = (struct anthy_segment_stat *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_segment_stat, 1);
    result = (int) ((arg1)->seg_len);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_SegmentStat_allocate(VALUE self) {
#else
    static VALUE
    _wrap_SegmentStat_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_anthy_segment_stat);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_SegmentStat(int argc, VALUE *argv, VALUE self) {
    struct anthy_segment_stat *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct anthy_segment_stat *)(struct anthy_segment_stat *) calloc(1, sizeof(struct anthy_segment_stat));
    DATA_PTR(self) = result;
    return self;
}


static void
free_anthy_segment_stat(struct anthy_segment_stat *arg1) {
    free((char *) arg1);
}
static VALUE
_wrap_PredictionStat_nr_prediction_set(int argc, VALUE *argv, VALUE self) {
    struct anthy_prediction_stat *arg1 = (struct anthy_prediction_stat *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_prediction_stat, 1);
    arg2 = NUM2INT(argv[0]);
    if (arg1) (arg1)->nr_prediction = arg2;
    
    return Qnil;
}


static VALUE
_wrap_PredictionStat_nr_prediction_get(int argc, VALUE *argv, VALUE self) {
    struct anthy_prediction_stat *arg1 = (struct anthy_prediction_stat *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_prediction_stat, 1);
    result = (int) ((arg1)->nr_prediction);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_PredictionStat_allocate(VALUE self) {
#else
    static VALUE
    _wrap_PredictionStat_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_anthy_prediction_stat);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_PredictionStat(int argc, VALUE *argv, VALUE self) {
    struct anthy_prediction_stat *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct anthy_prediction_stat *)(struct anthy_prediction_stat *) calloc(1, sizeof(struct anthy_prediction_stat));
    DATA_PTR(self) = result;
    return self;
}


static void
free_anthy_prediction_stat(struct anthy_prediction_stat *arg1) {
    free((char *) arg1);
}
static VALUE
_wrap_init(int argc, VALUE *argv, VALUE self) {
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (int)anthy_init();
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_quit(int argc, VALUE *argv, VALUE self) {
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    anthy_quit();
    
    return Qnil;
}


static VALUE
_wrap_conf_override(int argc, VALUE *argv, VALUE self) {
    char *arg1 = (char *) 0 ;
    char *arg2 = (char *) 0 ;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    arg1 = StringValuePtr(argv[0]);
    arg2 = StringValuePtr(argv[1]);
    anthy_conf_override((char const *)arg1,(char const *)arg2);
    
    return Qnil;
}


static VALUE
_wrap_set_personality(int argc, VALUE *argv, VALUE self) {
    char *arg1 = (char *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    arg1 = StringValuePtr(argv[0]);
    result = (int)anthy_set_personality((char const *)arg1);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_anthy_commit_prediction(int argc, VALUE *argv, VALUE self) {
    anthy_context_t arg1 = (anthy_context_t) 0 ;
    int arg2 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[1]);
    result = (int)anthy_commit_prediction(arg1,arg2);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_get_version_string(int argc, VALUE *argv, VALUE self) {
    char *result;
    VALUE vresult = Qnil;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (char *)anthy_get_version_string();
    
    vresult = rb_str_new2(result);
    return vresult;
}


static VALUE
_wrap_anthy_set_reconversion_mode(int argc, VALUE *argv, VALUE self) {
    anthy_context_t arg1 = (anthy_context_t) 0 ;
    int arg2 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(argv[0], (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[1]);
    result = (int)anthy_set_reconversion_mode(arg1,arg2);
    
    vresult = INT2NUM(result);
    return vresult;
}


#ifdef HAVE_RB_DEFINE_ALLOC_FUNC
static VALUE
_wrap_Context_allocate(VALUE self) {
#else
    static VALUE
    _wrap_Context_allocate(int argc, VALUE *argv, VALUE self) {
#endif
        
        
        VALUE vresult = SWIG_NewClassInstance(self, SWIGTYPE_p_anthy_context);
#ifndef HAVE_RB_DEFINE_ALLOC_FUNC
        rb_obj_call_init(vresult, argc, argv);
#endif
        return vresult;
    }
    

static VALUE
_wrap_new_Context(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *result;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    result = (struct anthy_context *)new_anthy_context();
    DATA_PTR(self) = result;
    return self;
}


static VALUE
_wrap_Context_reset(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    anthy_context_reset(arg1);
    
    return Qnil;
}


static VALUE
_wrap_Context_set_string(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    char *arg2 = (char *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (int)anthy_context_set_string(arg1,arg2);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_Context_resize_segment(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    int arg3 ;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = NUM2INT(argv[1]);
    anthy_context_resize_segment(arg1,arg2,arg3);
    
    return Qnil;
}


static VALUE
_wrap_Context_get_stat(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    struct anthy_conv_stat *arg2 = (struct anthy_conv_stat *) 0 ;
    int result;
    VALUE temp2 ;
    VALUE vresult = Qnil;
    
    {
        temp2 = rb_funcall(cConvStat.klass, rb_intern("new"), 0);
        Data_Get_Struct(temp2, struct anthy_conv_stat, arg2);
    }
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    result = (int)anthy_context_get_stat(arg1,arg2);
    
    vresult = INT2NUM(result);
    {
        if (vresult < 0)
        vresult = Qnil;
        else
        vresult = temp2;
    }
    return vresult;
}


static VALUE
_wrap_Context_get_segment_stat(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    struct anthy_segment_stat *arg3 = (struct anthy_segment_stat *) 0 ;
    int result;
    VALUE temp3 ;
    VALUE vresult = Qnil;
    
    {
        temp3 = rb_funcall(cSegmentStat.klass, rb_intern("new"), 0);
        Data_Get_Struct(temp3, struct anthy_segment_stat, arg3);
    }
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    result = (int)anthy_context_get_segment_stat(arg1,arg2,arg3);
    
    vresult = INT2NUM(result);
    {
        if (vresult < 0)
        vresult = Qnil;
        else
        vresult = temp3;
    }
    return vresult;
}


static VALUE
_wrap_Context_get_segment(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    int arg3 ;
    VALUE result;
    VALUE vresult = Qnil;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = NUM2INT(argv[1]);
    result = (VALUE)anthy_context_get_segment(arg1,arg2,arg3);
    
    vresult = result;
    return vresult;
}


static VALUE
_wrap_Context_commit_segment(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    int arg3 ;
    VALUE result;
    VALUE vresult = Qnil;
    
    if ((argc < 2) || (argc > 2))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 2)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    arg3 = NUM2INT(argv[1]);
    result = (VALUE)anthy_context_commit_segment(arg1,arg2,arg3);
    
    vresult = result;
    return vresult;
}


static VALUE
_wrap_Context_set_prediction_string(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    char *arg2 = (char *) 0 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = StringValuePtr(argv[0]);
    result = (int)anthy_context_set_prediction_string(arg1,(char const *)arg2);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_Context_get_prediction_stat(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    struct anthy_prediction_stat *arg2 = (struct anthy_prediction_stat *) 0 ;
    int result;
    VALUE temp2 ;
    VALUE vresult = Qnil;
    
    {
        temp2 = rb_funcall(cPredictionStat.klass, rb_intern("new"), 0);
        Data_Get_Struct(temp2, struct anthy_prediction_stat, arg2);
    }
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    result = (int)anthy_context_get_prediction_stat(arg1,arg2);
    
    vresult = INT2NUM(result);
    {
        if (vresult < 0)
        vresult = Qnil;
        else
        vresult = temp2;
    }
    return vresult;
}


static VALUE
_wrap_Context_get_prediction(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    int result;
    VALUE vresult = Qnil;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    result = (int)anthy_context_get_prediction(arg1,arg2);
    
    vresult = INT2NUM(result);
    return vresult;
}


static VALUE
_wrap_Context_print(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    
    if ((argc < 0) || (argc > 0))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 0)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    anthy_context_print(arg1);
    
    return Qnil;
}


static VALUE
_wrap_Context_set_encoding(int argc, VALUE *argv, VALUE self) {
    struct anthy_context *arg1 = (struct anthy_context *) 0 ;
    int arg2 ;
    
    if ((argc < 1) || (argc > 1))
    rb_raise(rb_eArgError, "wrong # of arguments(%d for 1)",argc);
    SWIG_ConvertPtr(self, (void **) &arg1, SWIGTYPE_p_anthy_context, 1);
    arg2 = NUM2INT(argv[0]);
    anthy_context_set_encoding(arg1,arg2);
    
    return Qnil;
}


static void
free_anthy_context(struct anthy_context *arg1) {
    free((char *) arg1);
}

/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_unsigned_long[] = {{"_p_unsigned_long", 0, "unsigned long *|VALUE *", 0, 0, 0, 0},{"_p_unsigned_long", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_anthy_conv_stat[] = {{"_p_anthy_conv_stat", 0, "struct anthy_conv_stat *", 0, 0, 0, 0},{"_p_anthy_conv_stat", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_anthy_segment_stat[] = {{"_p_anthy_segment_stat", 0, "struct anthy_segment_stat *", 0, 0, 0, 0},{"_p_anthy_segment_stat", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_anthy_context[] = {{"_p_anthy_context", 0, "struct anthy_context *", 0, 0, 0, 0},{"_p_anthy_context", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};
static swig_type_info _swigt__p_anthy_prediction_stat[] = {{"_p_anthy_prediction_stat", 0, "struct anthy_prediction_stat *", 0, 0, 0, 0},{"_p_anthy_prediction_stat", 0, 0, 0, 0, 0, 0},{0, 0, 0, 0, 0, 0, 0}};

static swig_type_info *swig_types_initial[] = {
_swigt__p_unsigned_long, 
_swigt__p_anthy_conv_stat, 
_swigt__p_anthy_segment_stat, 
_swigt__p_anthy_context, 
_swigt__p_anthy_prediction_stat, 
0
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */


#ifdef __cplusplus
extern "C"
#endif
SWIGEXPORT(void) Init_anthy(void) {
    int i;
    
    SWIG_InitRuntime();
    mAnthy = rb_define_module("Anthy");
    
    for (i = 0; swig_types_initial[i]; i++) {
        swig_types[i] = SWIG_TypeRegister(swig_types_initial[i]);
        SWIG_define_class(swig_types[i]);
    }
    
    
    anthy_init();
    
    rb_define_module_function(mAnthy, "version_string", _wrap_version_string, -1);
    
    rb_gc_register_address(&logger);
    
    rb_define_module_function(mAnthy, "set_logger", _wrap_set_logger, -1);
    
    cConvStat.klass = rb_define_class_under(mAnthy, "ConvStat", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_anthy_conv_stat, (void *) &cConvStat);
    rb_define_alloc_func(cConvStat.klass, _wrap_ConvStat_allocate);
    rb_define_method(cConvStat.klass, "initialize", _wrap_new_ConvStat, -1);
    rb_define_method(cConvStat.klass, "nr_segment=", _wrap_ConvStat_nr_segment_set, -1);
    rb_define_method(cConvStat.klass, "nr_segment", _wrap_ConvStat_nr_segment_get, -1);
    cConvStat.mark = 0;
    cConvStat.destroy = (void (*)(void *)) free_anthy_conv_stat;
    
    cSegmentStat.klass = rb_define_class_under(mAnthy, "SegmentStat", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_anthy_segment_stat, (void *) &cSegmentStat);
    rb_define_alloc_func(cSegmentStat.klass, _wrap_SegmentStat_allocate);
    rb_define_method(cSegmentStat.klass, "initialize", _wrap_new_SegmentStat, -1);
    rb_define_method(cSegmentStat.klass, "nr_candidate=", _wrap_SegmentStat_nr_candidate_set, -1);
    rb_define_method(cSegmentStat.klass, "nr_candidate", _wrap_SegmentStat_nr_candidate_get, -1);
    rb_define_method(cSegmentStat.klass, "seg_len=", _wrap_SegmentStat_seg_len_set, -1);
    rb_define_method(cSegmentStat.klass, "seg_len", _wrap_SegmentStat_seg_len_get, -1);
    cSegmentStat.mark = 0;
    cSegmentStat.destroy = (void (*)(void *)) free_anthy_segment_stat;
    
    cPredictionStat.klass = rb_define_class_under(mAnthy, "PredictionStat", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_anthy_prediction_stat, (void *) &cPredictionStat);
    rb_define_alloc_func(cPredictionStat.klass, _wrap_PredictionStat_allocate);
    rb_define_method(cPredictionStat.klass, "initialize", _wrap_new_PredictionStat, -1);
    rb_define_method(cPredictionStat.klass, "nr_prediction=", _wrap_PredictionStat_nr_prediction_set, -1);
    rb_define_method(cPredictionStat.klass, "nr_prediction", _wrap_PredictionStat_nr_prediction_get, -1);
    cPredictionStat.mark = 0;
    cPredictionStat.destroy = (void (*)(void *)) free_anthy_prediction_stat;
    rb_define_const(mAnthy,"NTH_UNCONVERTED_CANDIDATE", INT2NUM(-1));
    rb_define_const(mAnthy,"NTH_KATAKANA_CANDIDATE", INT2NUM(-2));
    rb_define_const(mAnthy,"NTH_HIRAGANA_CANDIDATE", INT2NUM(-3));
    rb_define_const(mAnthy,"NTH_HALFKANA_CANDIDATE", INT2NUM(-4));
    rb_define_const(mAnthy,"COMPILED_ENCODING", INT2NUM(0));
    rb_define_const(mAnthy,"EUC_JP_ENCODING", INT2NUM(1));
    rb_define_const(mAnthy,"UTF8_ENCODING", INT2NUM(2));
    rb_define_const(mAnthy,"ANTHY_RECONVERT_AUTO", INT2NUM(0));
    rb_define_const(mAnthy,"ANTHY_RECONVERT_DISABLE", INT2NUM(1));
    rb_define_const(mAnthy,"ANTHY_RECONVERT_ALWAYS", INT2NUM(2));
    rb_define_module_function(mAnthy, "init", _wrap_init, -1);
    rb_define_module_function(mAnthy, "quit", _wrap_quit, -1);
    rb_define_module_function(mAnthy, "conf_override", _wrap_conf_override, -1);
    rb_define_module_function(mAnthy, "set_personality", _wrap_set_personality, -1);
    rb_define_module_function(mAnthy, "anthy_commit_prediction", _wrap_anthy_commit_prediction, -1);
    rb_define_module_function(mAnthy, "get_version_string", _wrap_get_version_string, -1);
    rb_define_module_function(mAnthy, "anthy_set_reconversion_mode", _wrap_anthy_set_reconversion_mode, -1);
    
    cContext.klass = rb_define_class_under(mAnthy, "Context", rb_cObject);
    SWIG_TypeClientData(SWIGTYPE_p_anthy_context, (void *) &cContext);
    rb_define_alloc_func(cContext.klass, _wrap_Context_allocate);
    rb_define_method(cContext.klass, "initialize", _wrap_new_Context, -1);
    rb_define_method(cContext.klass, "reset", _wrap_Context_reset, -1);
    rb_define_method(cContext.klass, "set_string", _wrap_Context_set_string, -1);
    rb_define_alias(cContext.klass, "string=", "set_string");
    rb_define_method(cContext.klass, "resize_segment", _wrap_Context_resize_segment, -1);
    rb_define_method(cContext.klass, "get_stat", _wrap_Context_get_stat, -1);
    rb_define_alias(cContext.klass, "stat", "get_stat");
    rb_define_method(cContext.klass, "get_segment_stat", _wrap_Context_get_segment_stat, -1);
    rb_define_alias(cContext.klass, "segment_stat", "get_segment_stat");
    rb_define_method(cContext.klass, "get_segment", _wrap_Context_get_segment, -1);
    rb_define_alias(cContext.klass, "segment", "get_segment");
    rb_define_method(cContext.klass, "commit_segment", _wrap_Context_commit_segment, -1);
    rb_define_method(cContext.klass, "set_prediction_string", _wrap_Context_set_prediction_string, -1);
    rb_define_alias(cContext.klass, "prediction_string=", "set_prediction_string");
    rb_define_method(cContext.klass, "get_prediction_stat", _wrap_Context_get_prediction_stat, -1);
    rb_define_alias(cContext.klass, "prediction_stat", "get_prediction_stat");
    rb_define_method(cContext.klass, "get_prediction", _wrap_Context_get_prediction, -1);
    rb_define_alias(cContext.klass, "prediction", "get_prediction");
    rb_define_method(cContext.klass, "print", _wrap_Context_print, -1);
    rb_define_method(cContext.klass, "set_encoding", _wrap_Context_set_encoding, -1);
    rb_define_alias(cContext.klass, "encoding=", "set_encoding");
    cContext.mark = 0;
    cContext.destroy = (void (*)(void *)) anthy_release_context;
}

