/** 文節のクラス */
#ifndef _segclass_h_included_
#define _segclass_h_included_

enum dep_class {
  DEP_NONE,
  DEP_FUZOKUGO,
  DEP_NO,
  DEP_KAKUJOSHI,
  DEP_RENYOU,
  DEP_RENTAI,
  DEP_END,
  DEP_RAW
};


enum seg_class {
  SEG_HEAD,
  SEG_TAIL,
  SEG_BUNSETSU,
  SEG_SHUGO,
  SEG_JYUTSUGO,
  SEG_SHUSHOKUGO,
  SEG_SETSUZOKUGO,
  SEG_DOKURITSUGO,
  SEG_FUZOKUGO,
  SEG_HIRAKIKAKKO,
  SEG_TOJIKAKKO,
  SEG_MEISHI_KAKUJOSHI,
  SEG_MEISHI_SHUTAN,
  SEG_DOUSHI,
  SEG_DOUSHI_FUZOKUGO,
  SEG_DOUSHI_SHUTAN,
  SEG_KEIYOUSHI,
  SEG_KEIYOUSHI_FUZOKUGO,
  SEG_KEIYOUSHI_SHUTAN,
  SEG_KEIYOUDOUSHI,
  SEG_KEIYOUDOUSHI_FUZOKUGO,
  SEG_KEIYOUDOUSHI_SHUTAN,
  SEG_RENYOU_SHUSHOKU,
  SEG_RENTAI_SHUSHOKU,
  SEG_MEISHI,
  SEG_MEISHI_FUZOKUGO,
  SEG_MEISHI_RENYOU,
  SEG_DOUSHI_RENYOU,
  SEG_KEIYOUSHI_RENYOU,
  SEG_KEIYOUDOUSHI_RENYOU,
  SEG_FUKUSHI,
  SEG_DOUSHI_RENTAI,
  SEG_KEIYOUSHI_RENTAI,
  SEG_KEIYOUDOUSHI_RENTAI,
  SEG_RENTAISHI,
  SEG_KAKUJOSHI,
  SEG_RENYOU,
  SEG_RENTAI,
  SEG_SHUTAN,
  SEG_SIZE
};

int anthy_seg_class_is_depword(enum seg_class sc);

#endif
